spring:
  data:
    mongodb:
      username: jack
      password: "12345" #tiene que ser string
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090