spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    root: DEBUG
    com.dev.ecommerce: DEBUG
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-services"

